name: Run WPF .NET App with Wine on macOS ARM

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-wine-and-capture:
    runs-on: macos-latest  # 使用最新的 macOS 运行器，通常包括 M1 (ARM64)
    timeout-minutes: 30    # 设置整个 job 的超时时间为 30 分钟，防止无限等待
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 安装 Homebrew
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh )"
          
          # 安装 Wine (从 Homebrew 安装最新版本)
          brew install --cask wine-stable  # 或尝试 wine-devel
          
          # 安装 XQuartz (Wine 可能需要 X11 显示服务器)
          brew install --cask xquartz
          
          # 安装 winetricks (用于安装 Wine 所需的额外依赖，如 .NET Framework)
          brew install winetricks
          
          # 安装截图工具
          brew install imagemagick

      - name: Configure Wine environment for WPF .NET (Optimized)
        run: |
          # 设置 Wine 架构和前缀
          export WINEARCH=win64
          export WINEPREFIX=$HOME/.wine

          # 初始化 Wine 配置（非交互式，设置 Windows 版本为 win10）
          wineboot --init
          # 设置 Windows 版本为 Windows 10 可能对兼容性有帮助
          winecfg -v win10 &

          # 使用 winetricks 安装核心依赖，尝试避免或自动处理任何弹出窗口
          # 安装 .NET Framework 4.5 和 DirectX 9 (d3dx9)
          # 添加超时设置，防止无限等待
          timeout 1500 winetricks --force -q dotnet45  # 1500 秒 = 25 分钟
          
          # 检查上一条命令的退出状态
          if [ $? -eq 124 ]; then
              echo "Winetricks dotnet45 installation timed out, but proceeding anyway."
          fi
          
          # 安装 DirectX 9 依赖（通常较快）
          winetricks -q d3dx9

      - name: Download the WPF .NET EXE
        run: |
          # 下载指定的 Windows WPF 程序
          curl -L -o PCL2_CE_Release_ARM64.exe https://github.com/PCL-Community/PCL2-CE/releases/download/2.12.3/PCL2_CE_Release_ARM64.exe 

      - name: Run the WPF EXE with Wine and capture screenshot
        run: |
          # 启动 XQuartz
          open -a XQuartz &
          sleep 5  # 等待 XQuartz 启动
          
          # 设置 DISPLAY 环境变量
          export DISPLAY=:0
          
          # 设置 Wine 的 Windows 版本为 Windows 10 (尝试提升兼容性)
          winecfg -v win10
          
          # 使用 Wine 运行 WPF 程序，并等待一段时间让窗口出现
          # 注意：WPF 程序可能需要更长的启动时间
          wine PCL2_CE_Release_ARM64.exe &
          WINE_PID=$!
          
          # 等待足够时间让 WPF 程序启动和渲染 (WPF 应用启动可能较慢)
          sleep 20
          
          # 使用 screencapture 截图
          screencapture screenshot.png
          
          # 如果程序仍在运行，则终止它
          kill $WINE_PID || true

      - name: Upload screenshot to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wpf-wine-screenshot
          path: screenshot.png
