name: Run HMCL on macOS M1

on:
  workflow_dispatch:

jobs:
  run-hmcl:
    runs-on: macos-latest  # macOS 14 默认是 Apple Silicon (M1/M2)
    steps:
      - name: 安装 Java 11
        run: |
          brew install openjdk@11
          echo 'export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"' >> ~/.zprofile
          source ~/.zprofile
          java -version

      - name: 下载 HMCL
        run: |
          curl -L -o HMCL.jar https://github.com/HMCL-dev/HMCL/releases/download/release-3.6.16/HMCL-3.6.16.jar

      - name: 启动 HMCL（后台运行）
        run: |
          nohup java -jar HMCL.jar > hmcl.log 2>&1 &
          sleep 10  # 等待程序启动

      - name: 截图 HMCL 窗口
        run: |
          screencapture -x hmcl_screenshot.png

      - name: 上传截图到 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HMCL-Screenshot
          path: hmcl_screenshot.png
